### ISSUE TITLE
SE CONNECTER

### ISSUE THREAD

**Issue by Pomzed** [mr-am/tp_eshop#1]
SE CONNECTER 
J'ai tenté de me connecter directement, en utilisant un mail et un mdp au pif ==> 2 erreurs

 Notice: Undefined variable: valeur2 in /home/was208/sites/tp_eshop/login/index.php on line 50
Call Stack
# Time    Memory  Function    Location

1   0.0001  233384  {main}( )   ../index.php:0
2   0.0013  239696  require( '/home/was208/sites/tp_eshop/views/index.phtml' )  ../index.php:102
3   0.0013  240768  require( '/home/was208/sites/tp_eshop/login/index.php' )    ../index.phtml:21

Notice: Undefined index: in /home/was208/sites/tp_eshop/login/index.php on line 50
Call Stack
# Time    Memory  Function    Location

1   0.0001  233384  {main}( )   ../index.php:0
2   0.0013  239696  require( '/home/was208/sites/tp_eshop/views/index.phtml' )  ../index.php:102
3   0.0013  240768  require( '/home/was208/sites/tp_eshop/login/index.php' )    ../index.phtml:21

**Comment by PatrickNeff** [comment]
un simple résidu de copier collé. A voir pour celui qui  a codé la page

**Comment by mr-am** [comment]
Corrigé
