### ISSUE TITLE
Donner son avis

### ISSUE THREAD

**Issue by Shadownest** [mr-am/tp_eshop#13]
URL : http://10.32.195.206/tp_eshop/index.php?page=note&id_product=1
Erreur : ( ! ) Fatal error: Call to a member function fetchAll() on a non-object in /home/was208/sites/tp_eshop/note/index.php on line 75

**Comment by Shadownest** [comment]
URL : http://10.32.195.206/tp_eshop/index.php?page=note
Erreur1 : ( ! ) Notice: Undefined index: id_product in /home/was208/sites/tp_eshop/note/index.php on line 47
Erreur2 : ( ! ) Fatal error: Call to a member function fetch() on a non-object in /home/was208/sites/tp_eshop/note/index.php on line 47

**Comment by mr-am** [comment]
Corrigé
