### ISSUE TITLE
 Fatal error: Call to a member function fetchAll() on a non-object in /home/was208/sites/tp_eshop/note/index.php on line 81

### ISSUE THREAD

**Issue by p-steve** [mr-am/tp_eshop#3]
quand je veux faire un nouveau commentaire

**Comment by PatrickNeff** [comment]
On ne devrais pas laisser apparaitre le bouton pour laisser un message sans être loggué.
Ou alors on laisse passer, mais avec un statut invité ce qui rendrais la note non visible (bien qu'enregistré en base)

**Comment by mr-am** [comment]
Corrigé ...
